version: '3.9'

services:
  # ==========================
  # BASES DE DATOS
  # ==========================
  postgres_db:
    image: ankane/pgvector:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  mysql_db:
    image: mysql:8.0
    restart: always
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  mariadb_db:
    image: mariadb:10.6
    restart: always
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app_network

  redis:
    image: redis:7.2
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - app_network

  # ==========================
  # HERRAMIENTAS DE ADMINISTRACIÓN
  # ==========================
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres_db
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_container
    restart: always
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: mysql_db,mariadb_db
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "8082:80"
    depends_on:
      - mysql_db
      - mariadb_db
    networks:
      - app_network

  adminer:
    image: adminer:latest
    container_name: adminer_container
    restart: always
    ports:
      - "8083:8080"
    networks:
      - app_network

  # ==========================
  # MONITOREO Y DASHBOARDS
  # ==========================
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_container
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    networks:
      - app_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_container
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - postgres_db
      - mysql_db
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - app_network

  # ==========================
  # ANÁLISIS DE DATOS Y BI
  # ==========================
  metabase:
    image: metabase/metabase:latest
    container_name: metabase_container
    restart: always
    ports:
      - "3001:3000"
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    volumes:
      - metabase_data:/metabase-data
    depends_on:
      - postgres_db
      - mysql_db
    networks:
      - app_network

  superset:
    image: apache/superset:latest
    container_name: superset_container
    restart: always
    ports:
      - "8088:8088"
    environment:
      SUPERSET_LOAD_EXAMPLES: "no"
      SUPERSET_SECRET_KEY: "superset_secret"
    depends_on:
      - postgres_db
    volumes:
      - superset_data:/app/superset_home
    networks:
      - app_network

  # ==========================
  # ALMACENAMIENTO S3 LOCAL
  # ==========================
  minio:
    image: minio/minio:latest
    container_name: minio_container
    restart: always
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - app_network

volumes:
  postgres_data:
  mysql_data:
  mariadb_data:
  redis_data:
  pgadmin_data:
  prometheus_data:
  grafana_data:
  metabase_data:
  superset_data:
  minio_data:

networks:
  app_network:
    driver: bridge
